server:
  port: 8200

spring:
  application:
    name: upload-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

baidu:
  upload:
    path:
      windows: D:\\images
      linux: /yanxinlong/images
    img:
     host: http://image.mrshop.com
