server:
  port: 8088

spring:
  application:
    name: eureka-zuul

zuul:
  # 路由前缀
  prefix: /api
  # 声明路由
  routes:
    xxx-server: /manage/**
    search-server: /search/**
    user-server: /user-center/**
    oauth-server: /oauth-center/**
    car-server: /car/**
  #  api-xxx:
  #    # 声明将所有以/api-ribbon/的请求都转发到eureka-ribbon的服务中
  #    path: /api-xxx/**
  #    serviceId: xxx-server
  #  api-search:
  #    path: /api-search/**
  #    serviceId: search-server
  # 启用重试
  retryable: true
  # 包含此路径的不进行路由
  ignored-patterns: /upload/**
  # 忽略上传服务
  ignored-services:
    -upload-server
  add-host-header: true
  sensitive-headers:

#配置负载
ribbon:
  ConnectTimeout: 3000 # 连接超时时间(ms)
  ReadTimeout: 3000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 2 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000 # 熔断超时时长：6000ms

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

mrshop:
  #声明不进行拦截的请求用,分隔
  filter:
    excludes: /api/oauth-center/oauth/login,/api/user-center/user/register,/api/search/es/search
  jwt:
    pubKeyPath: D:\rea.pub # 公钥地址(私钥加密,公钥解密)
    cookieName: MRSHOP_TOKEN

