server:
  port: 8700

spring:
  application:
    name: car-server
    # 整合redis配置
  redis:
    # 数据库标识，可以配置多个redis使用不同的标识区分
    database: 0
    # redisIP地址
    host: 81.70.229.244
    # redis端口号
    port: 6379
    # redis密码
    password: 123456
    # redis连接池的配置
    jedis:
      pool:
        #最大连接数据库连接数,设 0 为没有限制
        max-active: 8
        #最大等待连接中的数量,设 0 为没有限制
        max-idle: 8
        #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        max-wait: -1ms
        #最小等待连接中的数量,设 0 为没有限制
        min-idle: 0

#日志设置
logging:
  level:
    # 打印与我们程序相关的日志信息
    com.baidu.shop: debug
# eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


mrshop:
  jwt:
    pubKeyPath: D:\rea.pub # 公钥地址
    cookieName: MRSHOP_TOKEN # cookie的名称